openapi: 3.0.3
info:
  title: Dona edu API
  version: 0.1.0
  license:
    name: Proprietary
    url: https://donasky.com/license
servers:
  - url: https://donasky.com
  - url: http://localhost:8080

tags:


paths:


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
